-- This code breaks schema.sql

-- CREATE TABLE employee (
--   id INTEGER PRIMARY KEY,
--   first_name VARCHAR(30) NOT NULL,
--   last_name VARCHAR(30) NOT NULL,
--   -- hold reference to employee role
--   role_id INTEGER,
--   CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE SET NULL,
--     -- make NULL if employee has no manager (HOW?)
--   manager_id INTEGER,
--   CONSTRAINT fk_employee FOREIGN KEY (manager_id) REFERENCES employee(id) ON DELETE SET NULL
-- );